#!/usr/bin/env python3
"""RTLTracer single-file bundle. Generated by scripts/bundle.py — edit the package, not this file."""
from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
import argparse
import hashlib
import json
import os
import pathlib
import re
import sqlite3
import sys
import time

# --- __init__ --------------------------------------------------
__version__ = "0.1.0"

# --- sql -------------------------------------------------------
class _Sql:
    """Load a named SQL query. Disk-backed in the package (lazy, cached);
    the bundler builds one from an embedded {name: text} map instead."""

    def __init__(self, texts: dict[str, str] | None = None):
        self._cache: dict[str, str] = {} if texts is None else dict(texts)

    def load(self, name: str) -> str:
        if name not in self._cache:
            path = pathlib.Path(__file__).parent / "sql" / f"{name}.sql"
            self._cache[name] = path.read_text(encoding="utf-8")
        return self._cache[name]

    def in_list(self, nets: list[int]) -> str:
        """The ?,?,... placeholder string for an IN list."""
        return ",".join("?" * len(nets))

    def fill(self, name: str, nets: list[int]) -> tuple[str, list[int]]:
        """Expand a {nets} placeholder into concrete placeholders."""
        return self.load(name).replace("{nets}", self.in_list(nets)), nets


sql = _Sql()

# --- embedded SQL (replaces the disk-backed loader) ---
sql = _Sql({
    'body_local': "-- cone: nets that are subroutine body locals (formals and locals). One call\n-- shares them with another, so the walk must keep calls apart there. Read\n-- once for the design, never per net.\n--\n-- A subroutine name carries '_', a LIKE metacharacter, so matched literally\n-- by prefix rather than as a pattern.\nSELECT DISTINCT n.id AS net_id\nFROM net n\nJOIN call_site cs ON cs.inst_id = n.inst_id\nWHERE substr(n.name, 1, length(cs.subroutine_name) + 1) = cs.subroutine_name || '.'\n",
    'call_parents': '-- cone: which call-site expansion encloses which. Read once for the design.\nSELECT call_site_id, parent_call_site_id\nFROM v_call_site\n',
    'child_node': '-- resolve: one path segment down the elaborated tree.\nSELECT node_id, node_name, node_kind, inst_id, parent_node_id\nFROM v_tree_node\nWHERE parent_node_id = :parent AND node_name = :name\n',
    'children_of': '-- resolve: what is at one tree level, for a correction hint.\nSELECT node_name\nFROM v_tree_node\nWHERE parent_node_id = :parent\nORDER BY node_name\n',
    'dead_stmts': '-- cone: statements a constant condition rules out. A statement whose gating\n-- branch, or any ancestor of it, is statically not taken cannot run at this\n-- parameterisation; its arcs are still reported, marked unreachable. The\n-- gating branch lives on the statement (v_stmt.branch_id), not on the edge.\nSELECT stmt_id\nFROM v_stmt\nWHERE branch_id IN (\n    SELECT branch_id\n    FROM branch_ancestor\n    WHERE ancestor_branch_id IN (SELECT branch_id FROM v_branch WHERE static_taken = 0)\n)\n',
    'fanin_bfs': '-- cone (BFS engine): driving arcs of a set of nets, one batch per walk\n-- level. The view is presented traversal-oriented: the frontier net is\n-- `near`, the edge leads `near -> far`.\nSELECT d.edge_source,\n       d.edge_id,\n       d.src_net_id, d.dst_net_id,\n       d.dst_net_id AS near_net_id, d.src_net_id AS far_net_id,\n       d.dst_lo AS near_lo, d.dst_hi AS near_hi,\n       d.src_lo AS far_lo, d.src_hi AS far_hi,\n       d.map_kind, d.edge_kind,\n       d.dep_id, d.stmt_id,\n       d.call_site_id,\n       d.file_path, d.src_line\nFROM v_trace_edge d\nWHERE d.dst_net_id IN ({nets})\n  AND d.src_net_id IS NOT NULL\n',
    'fanout_bfs': '-- cone (BFS engine): reading arcs of a set of nets, one batch per walk\n-- level. The view is presented traversal-oriented: the frontier net is\n-- `near`, the edge leads `near -> far`.\nSELECT d.edge_source,\n       d.edge_id,\n       d.src_net_id, d.dst_net_id,\n       d.src_net_id AS near_net_id, d.dst_net_id AS far_net_id,\n       d.src_lo AS near_lo, d.src_hi AS near_hi,\n       d.dst_lo AS far_lo, d.dst_hi AS far_hi,\n       d.map_kind, d.edge_kind,\n       d.dep_id, d.stmt_id,\n       d.call_site_id,\n       d.file_path, d.src_line\nFROM v_trace_edge d\nWHERE d.src_net_id IN ({nets})\n  AND d.dst_net_id IS NOT NULL\n',
    'find_instance': "-- find: tree levels whose own segment matches a glob, under the root.\nSELECT t.node_id,\n       t.node_name,\n       t.node_kind,\n       t.module_name,\n       t.def_name,\n       np.node_path\nFROM v_tree_node t\nJOIN v_node_path np ON np.node_id = t.node_id\nWHERE t.node_name GLOB :pattern\n  AND (np.node_path = :root_path OR np.node_path LIKE :root_path || '.%')\nORDER BY np.node_path\nLIMIT :limit;\n",
    'find_module': '-- find: definitions whose name matches a glob, with occurrence counts.\nSELECT m.name,\n       m.def_kind,\n       COUNT(i.id) AS occurrences\nFROM module m\nLEFT JOIN inst i ON i.module_id = m.id\nWHERE m.name GLOB :pattern\nGROUP BY m.id\nORDER BY m.name\nLIMIT :limit;\n',
    'find_net': "-- find: nets whose own name matches a glob, anywhere under the chosen root.\n-- :pattern is a SQLite GLOB pattern (*, ?); :root_path is the top's path.\nSELECT n.net_id,\n       n.inst_id,\n       n.net_name,\n       n.decl_kind,\n       n.width,\n       np.node_path,\n       np.node_path || '.' || n.net_name AS full_path\nFROM v_net n\nJOIN v_node_path np ON np.node_id = n.inst_id\nWHERE n.net_name GLOB :pattern\n  AND (np.node_path = :root_path OR np.node_path LIKE :root_path || '.%')\nORDER BY full_path\nLIMIT :limit;\n",
    'info': '-- info: the export seal, one row.\nSELECT schema_version, tool, tool_version, slang_version, producer_revision,\n       top, analysis_status, error_count, unresolved_count,\n       empty_procedure_count, duplicate_path_count, recursion_count,\n       truncated_call_count, checker_inst_count, unanalysed_inst_count,\n       config_digest\nFROM v_db_info;\n',
    'info_sources': '-- info: every source file the export read, its absolute path and SHA-256.\n-- The Python wrapper hashes the file on disk and compares digests.\nSELECT f.path AS file_path, sf.path AS src_path, sf.digest AS sha256\nFROM file f\nJOIN src_file sf ON sf.id = f.src_file_id\nORDER BY sf.path;\n',
    'info_unresolved': "-- info: hierarchical references the export could not resolve, by access.\nSELECT COALESCE(SUM(access = 'read'), 0)  AS unresolved_reads,\n       COALESCE(SUM(access = 'write'), 0) AS unresolved_writes\nFROM v_hier_ref\nWHERE resolved_net_id IS NULL;\n",
    'net_by_name': '-- resolve: a net declared in one instance, by its full local name\n-- (generate and subroutine segments included).\nSELECT net_id, inst_id, net_name, decl_kind, data_type, width,\n       scope_node_id, file_path, src_path, src_line, src_col\nFROM v_net\nWHERE inst_id = :inst_id AND net_name = :name\n',
    'net_exists': '-- resolve: whether an instance declares a net of this name (a hint check).\nSELECT 1\nFROM v_net\nWHERE inst_id = :inst_id AND net_name = :name\n',
    'net_names': "-- cone / trace: name a set of nets. {nets} is expanded to ?,?,...\nSELECT n.net_id,\n       n.inst_id,\n       n.net_name,\n       n.decl_kind,\n       n.data_type,\n       n.width,\n       n.scope_node_id,\n       np.node_path,\n       np.node_path || '.' || n.net_name AS full_path\nFROM v_net n\nJOIN v_node_path np ON np.node_id = n.inst_id\nWHERE n.net_id IN ({nets})\n",
    'nets_of': '-- resolve: nets of one instance, for a correction hint.\nSELECT net_name\nFROM v_net\nWHERE inst_id = :inst_id\nORDER BY net_name\n',
    'node_by_id': "-- resolve: a tree node's instance, by node id.\nSELECT node_id, inst_id\nFROM v_tree_node\nWHERE node_id = :node_id\n",
    'node_by_path': '-- tree: a tree level by its assembled path, when the scope is not a net.\nSELECT node_id, node_path\nFROM v_node_path\nWHERE node_path = :node_path\n',
    'node_paths': "-- trace: every node's assembled path. v_node_path walks the whole tree per\n-- query, so it is taken once and kept, never looked up per hop.\nSELECT node_id, node_path\nFROM v_node_path\n",
    'state_elements': "-- cone: state elements — nets a combinational walk stops at, with\n-- propagation across whole-width port ties.\n--\n-- Base set: nonblocking writes in an edge-sensitive procedure (clocked)\n-- and writes in always_latch (latch). Then the property is carried across\n-- every whole-width connection arc (src_lo/dst_lo both NULL): a flop's\n-- output wired whole to a port makes the far net a state element too.\n-- Half-width ties do not propagate.\n--\n-- Returns one row per state net: net_id + state_kind ('clocked'|'latch').\nWITH state_kind(net_id, kind) AS (\n    SELECT DISTINCT d.tgt_net_id,\n           CASE WHEN p.proc_kind = 'always_latch' THEN 'latch' ELSE 'clocked' END\n    FROM net_dep d\n    JOIN stmt s ON s.id = d.stmt_id\n    JOIN proc p ON p.id = s.proc_id\n    WHERE d.dep_kind = 'data'\n      AND (p.proc_kind = 'always_latch'\n           OR (s.assign_kind = 'nonblocking'\n               AND (p.proc_kind = 'always_ff'\n                    OR (p.proc_kind = 'always' AND EXISTS(\n                          SELECT 1 FROM proc_event e\n                          WHERE e.proc_id = p.id\n                            AND e.event_kind = 'sensitivity'\n                            AND e.edge_kind IS NOT NULL)))))\n),\nprop(net_id, kind) AS (\n    SELECT net_id, kind FROM state_kind\n  UNION\n    SELECT d.dst_net_id, p.kind\n    FROM prop p\n    JOIN v_trace_edge d ON d.src_net_id = p.net_id\n    WHERE d.edge_kind = 'connection'\n      AND d.src_lo IS NULL AND d.dst_lo IS NULL\n  UNION\n    SELECT d.src_net_id, p.kind\n    FROM prop p\n    JOIN v_trace_edge d ON d.dst_net_id = p.net_id\n    WHERE d.edge_kind = 'connection'\n      AND d.src_lo IS NULL AND d.dst_lo IS NULL\n)\nSELECT DISTINCT net_id, kind FROM prop\n",
    'tops': "-- resolve: the elaborated top(s), in id order.\nSELECT t.node_id, t.node_name\nFROM v_tree_node t\nWHERE t.node_kind = 'root'\nORDER BY t.node_id;\n",
    'trace_calls': '-- trace: the call string a row belongs to. Walked up parent_call_site_id\n-- by the wrapper; depth is small.\nSELECT call_site_id, parent_call_site_id, subroutine_name, depth\nFROM v_call_site\nWHERE call_site_id = :call_site_id;\n',
    'trace_driver': "-- trace: every recorded driving arc of one net, one row each, presented\n-- traversal-oriented (near = the traced net, far = the other endpoint).\n-- :ctl = 1 includes control (gating) arcs; 0 leaves them out.\nSELECT v.signal_net_id AS net_id,\n       v.signal_lo AS near_lo, v.signal_hi AS near_hi,\n       v.driver_net_id AS far_net_id,\n       v.driver_ref AS far_ref,\n       v.driver_lo AS far_lo, v.driver_hi AS far_hi,\n       v.map_kind,\n       v.driver_kind AS kind,\n       d.dep_kind AS dep_kind,\n       v.dep_id, v.conn_id, v.stmt_id, v.prim_id, v.term_id,\n       v.call_site_id, v.file_path, v.src_path, v.src_line, v.src_col\nFROM v_driver v\n-- v_driver carries the real driver_kind (not folded), but not dep_kind; the\n-- base fact distinguishes a constant (driver_kind='constant') as dep_kind='data'.\nLEFT JOIN net_dep d ON d.id = v.dep_id\nWHERE v.signal_net_id = :net_id\n  AND (:ctl = 1 OR v.driver_kind <> 'control')\n",
    'trace_events': "-- trace: the events one procedure triggers on.\nSELECT proc_event_id, proc_id, proc_kind, net_id, net_name,\n       event_kind, edge_kind, file_path, src_path, src_line, src_col\nFROM v_proc_event\nWHERE proc_id = :proc_id\n  AND event_kind = 'sensitivity'\nORDER BY proc_event_id;\n",
    'trace_gates': '-- trace: the gating chain of one statement, outermost first.\n-- branch_ancestor makes this one indexed lookup; reads come from\n-- branch_ref per level.\nSELECT v.depth,\n       v.branch_kind,\n       v.sense,\n       v.case_kind,\n       v.check_kind,\n       v.static_taken,\n       v.ordinal,\n       v.labels,\n       v.iter_name,\n       v.iter_first,\n       v.iter_step,\n       v.iter_count,\n       v.src_line,\n       (SELECT group_concat(n.net_name)\n          FROM branch_ref r JOIN v_net n ON n.net_id = r.net_id\n         WHERE r.branch_id = v.branch_id) AS reads\nFROM stmt s\nJOIN branch_ancestor a ON a.branch_id = s.branch_id\nJOIN v_branch v        ON v.branch_id = a.ancestor_branch_id\nWHERE s.id = :stmt_id\nORDER BY v.depth;\n',
    'trace_load': "-- trace: every recorded reading arc of one net, one row each, presented\n-- traversal-oriented (near = the traced net, far = the other endpoint).\n-- :ctl = 1 includes control (gating) reads; 0 leaves them out.\nSELECT v.signal_net_id AS net_id,\n       v.signal_lo AS near_lo, v.signal_hi AS near_hi,\n       v.load_net_id AS far_net_id,\n       v.load_ref AS far_ref,\n       v.load_lo AS far_lo, v.load_hi AS far_hi,\n       v.map_kind,\n       v.load_kind AS kind,\n       v.dep_kind,\n       v.dep_id, v.conn_id, v.stmt_id, v.proc_id, v.term_id,\n       v.call_site_id, v.branch_id, v.file_path, v.src_path, v.src_line, v.src_col\nFROM v_load v\nWHERE v.signal_net_id = :net_id\n  AND (:ctl = 1 OR COALESCE(v.dep_kind, '') <> 'control')\n",
    'trace_prockind': "-- trace: the procedure's own name for a proc_id.\nSELECT proc_kind\nFROM proc\nWHERE id = :proc_id;\n",
    'trace_procwrites': "-- trace: every statement of one procedure that writes one net, in\n-- execution order. Two sources: a local lvalue (v_stmt_target) and an\n-- outward write (hier_ref, access='write').\nSELECT s.sequence,\n       s.src_line,\n       s.branch_id,\n       s.call_site_id,\n       t.lo,\n       t.hi,\n       t.is_exact\nFROM v_stmt s\nJOIN v_stmt_target t ON t.stmt_id = s.stmt_id\nWHERE s.proc_id = :proc_id\n  AND t.net_id = :net_id\n  AND t.target_kind = 'written_by'\nUNION ALL\nSELECT s.sequence,\n       s.src_line,\n       s.branch_id,\n       s.call_site_id,\n       h.lo,\n       h.hi,\n       h.is_exact\nFROM v_stmt s\nJOIN hier_ref h ON h.stmt_id = s.stmt_id\nWHERE s.proc_id = :proc_id\n  AND h.resolved_net_id = :net_id\n  AND h.access = 'write'\nORDER BY sequence;\n",
    'trace_source': '-- trace: quote one source line, and know whether the file still hashes to\n-- what the export recorded. The wrapper reads the file at src_path and\n-- compares to sha256 before quoting.\nSELECT f.path AS file_path, sf.path AS src_path, sf.digest AS sha256\nFROM file f\nJOIN src_file sf ON sf.id = f.src_file_id\nWHERE f.path = :file_path;\n',
    'trace_stmt': '-- trace: statements reachable from a set of arc rows, for metadata the arc\n-- view does not carry (scope, procedure linkage, construct wording).\nSELECT stmt_id, scope_node_id, proc_id, construct, stmt_kind,\n       assign_kind, sequence, call_site_id,\n       file_path, src_line\nFROM v_stmt\nWHERE stmt_id IN ({nets})\n',
    'tree': "-- tree: depth-first levels under a root, with net and child counts.\n-- :root_node_id selects the starting level; :max_depth bounds recursion.\nWITH RECURSIVE walk(node_id, depth, path) AS (\n    SELECT t.node_id, 0, t.node_name\n    FROM v_tree_node t\n    WHERE t.node_id = :root_node_id\n  UNION ALL\n    SELECT c.node_id, w.depth + 1, w.path || '.' || c.node_name\n    FROM walk w\n    JOIN v_tree_node c ON c.parent_node_id = w.node_id\n    WHERE w.depth < :max_depth\n)\nSELECT w.depth,\n       w.path,\n       t.node_kind,\n       t.module_name,\n       t.def_name,\n       (SELECT COUNT(*) FROM v_net n WHERE n.scope_node_id = w.node_id) AS nets,\n       (SELECT COUNT(*) FROM v_tree_node c WHERE c.parent_node_id = w.node_id) AS children\nFROM walk w\nJOIN v_tree_node t ON t.node_id = w.node_id\nORDER BY w.path;\n",
})

# --- bits ------------------------------------------------------
# Sentinel: an edge the current bit window does not touch.
SKIP = object()


def propagate(window, near_lo, near_hi, far_lo, far_hi, map_kind):
    """Carry a bit window across one edge from near to far.

    Returns SKIP when the window does not touch the edge, None when
    precision is lost (the far side widens to the whole net), or the
    far-side (lo, hi) for an exact correspondence.
    """
    if window is None:
        return None
    wlo, whi = window
    if near_lo is not None and near_hi is not None:
        olo, ohi = max(wlo, near_lo), min(whi, near_hi)
        if olo > ohi:
            return SKIP                     # disjoint: edge feeds other bits
        overlap = (olo, ohi)
    elif near_lo is None and near_hi is None:
        overlap = (wlo, whi)                # whole net covers the window
    else:
        return None                         # unknown extent: widen
    if map_kind != "exact":
        return None                         # not an exact bit correspondence
    # exact ⇒ equal-width and offset-preserving. A whole end is implicitly
    # [0, width-1], so its base bit is 0; a concrete end bases at its lo. This
    # matches v_trace_edge, which normalizes a whole exact end the same way.
    if near_lo is not None and far_lo is not None and \
            (near_hi - near_lo) != (far_hi - far_lo):
        return None                         # concrete widths disagree
    near_base = near_lo if near_lo is not None else 0
    far_base = far_lo if far_lo is not None else 0
    return (far_base + overlap[0] - near_base,
            far_base + overlap[1] - near_base)


def merge_intervals(intervals: list[tuple[int, int]]) -> list[tuple[int, int]]:
    """Merge overlapping or adjacent [lo, hi] intervals into a canonical set."""
    out: list[tuple[int, int]] = []
    for lo, hi in sorted(intervals):
        if out and lo <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], hi))
        else:
            out.append((lo, hi))
    return out


def _subtract(window: tuple[int, int], covered: list[tuple[int, int]]) -> list[tuple[int, int]]:
    """Parts of `window` not already covered (covered is sorted and merged)."""
    lo, hi = window
    parts, cur = [], lo
    for ilo, ihi in covered:
        if ihi < cur:
            continue
        if ilo > hi:
            break
        if ilo > cur:
            parts.append((cur, min(ilo - 1, hi)))
        cur = max(cur, ihi + 1)
        if cur > hi:
            break
    if cur <= hi:
        parts.append((cur, hi))
    return parts


def uncovered(covered: dict, key, window: tuple[int, int] | None) -> list:
    """Mark `window` walked for `key`; return the parts not already walked
    (each None for the whole net, or a (lo, hi) range). [] if nothing is new."""
    cur = covered.get(key)
    if cur == "WHOLE":
        return []
    if window is None:
        covered[key] = "WHOLE"
        return [None]
    intervals = cur or []
    parts = _subtract(window, intervals)
    if not parts:
        return []
    covered[key] = merge_intervals(intervals + [window])
    return parts

# --- db --------------------------------------------------------
SCHEMA_VERSION = 22


@dataclass
class Db:
    path: str
    conn: sqlite3.Connection


class DbError(Exception):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


def open_db(path: str) -> Db:
    try:
        conn = sqlite3.connect(path)
    except sqlite3.Error as e:
        raise DbError("DB_UNREADABLE", f"cannot open '{path}': {e}")
    conn.row_factory = sqlite3.Row
    db = Db(path=path, conn=conn)
    try:
        row = conn.execute(sql.load("info")).fetchone()
    except sqlite3.Error as e:
        conn.close()
        raise DbError("DB_UNREADABLE", f"'{path}' is not a design database: {e}")
    if row is None:
        conn.close()
        raise DbError("DB_UNREADABLE", f"'{path}' has no v_db_info seal")
    version = row["schema_version"]
    if version != SCHEMA_VERSION:
        conn.close()
        raise DbError(
            "DB_UNREADABLE",
            f"schema v{version} is not readable; this build reads v{SCHEMA_VERSION}. Re-export the RTL with a matching rtl-designdb.",
        )
    return db


def net_names(cursor, net_ids) -> dict[int, str]:
    """Batch net-id -> full-path lookup for result assembly."""
    ids = sorted(set(net_ids))
    if not ids:
        return {}
    text, values = sql.fill("net_names", ids)
    return {r["net_id"]: r["full_path"] for r in cursor.execute(text, values)}

# --- source ----------------------------------------------------
def _candidate_paths(src: str, file_path: str) -> list[str]:
    """Paths to try when quoting source, in priority order. The recorded
    src_path is machine-specific; file_path is portable, and normalizing its
    separators also covers fixtures built on the other platform."""
    normalized = file_path.replace("\\", "/")
    return list(dict.fromkeys([src, file_path, normalized]))


def source_state(cursor, file_path: str) -> tuple[str, str, str | None]:
    """(src_path, sha256, state), where state is 'current'/'stale'/'missing'.
    Reads the file once to hash it against the recorded digest."""
    row = cursor.execute(sql.load("trace_source"), {"file_path": file_path}).fetchone()
    if row is None:
        return file_path, "", "missing"
    src = row["src_path"]
    digest = row["sha256"]
    # Try every candidate before giving up: an earlier path may exist but
    # hold stale bytes, while a later one still matches the recorded digest.
    stale_cand = None
    for cand in _candidate_paths(src, file_path):
        try:
            data = Path(cand).read_bytes()
        except OSError:
            continue
        if hashlib.sha256(data).hexdigest() == digest:
            return cand, digest, "current"
        if stale_cand is None:
            stale_cand = cand
    if stale_cand is not None:
        return stale_cand, digest, "stale"
    return src, digest, "missing"


class Source:
    """Quotes source lines, hashing each file and holding its split lines once,
    so repeated lookups in one command touch the disk once per file."""

    def __init__(self, cursor):
        self.cursor = cursor
        self._state: dict[str, tuple[str, str, str | None]] = {}
        self._lines: dict[str, list[str] | None] = {}

    def line(self, file_path: str, line: int | None) -> tuple[str | None, str]:
        if file_path not in self._state:
            self._state[file_path] = source_state(self.cursor, file_path)
        src, _digest, state = self._state[file_path]
        # Only quote source that still matches the DB digest.  Stale bytes
        # would not be the statement the dependency was recorded against.
        if state != "current" or line is None:
            return None, state
        lines = self._read(file_path, src)
        if lines is None:
            return None, "missing"
        return (lines[line - 1].strip() if 1 <= line <= len(lines) else None), state

    def _read(self, file_path: str, src: str) -> list[str] | None:
        if file_path not in self._lines:
            lines = None
            for cand in _candidate_paths(src, file_path):
                try:
                    lines = Path(cand).read_text(
                        encoding="utf-8", errors="replace").splitlines()
                    break
                except OSError:
                    continue
            self._lines[file_path] = lines
        return self._lines[file_path]

# --- resolve ---------------------------------------------------
_SEPS = {".", "/"}
_BIT_SELECT = re.compile(r"^(.*)\[(\d+)(?::(\d+))?\]$")
_OFFSET_SELECT = re.compile(r"^(.*)@\[(\d+)(?::(\d+))?\]$")
_RANGE = re.compile(r"\[(\d+)\s*:\s*(\d+)\]")


@dataclass
class ResolvedSignal:
    net_id: int
    inst_id: int
    net_name: str
    node_path: str
    full_path: str
    width: int | None
    spell: str | None = None
    # The selected bits as flattened LSB-relative offsets, closed [lo, hi];
    # None means the whole net. This is what the cone walk carries.
    window: tuple[int, int] | None = None


class ResolveError(Exception):
    def __init__(self, code: str, message: str):
        super().__init__(message)
        self.code = code
        self.message = message


def _segments(path: str) -> list[str]:
    out, cur = [], ""
    for ch in path:
        if ch in _SEPS:
            if cur:
                out.append(cur)
                cur = ""
        else:
            cur += ch
    if cur:
        out.append(cur)
    return out


def _levels_of(path: str) -> list[str]:
    """Split a path into levels. An escaped identifier may hold a
    separator; LRM 5.6.1 ends it at whitespace, so the segments that
    belong to one level are joined back with '.'."""
    segs = _segments(path)
    levels = []
    i = 0
    while i < len(segs):
        if segs[i].startswith("\\") and not segs[i][-1:].isspace():
            j = i + 1
            while j < len(segs) and not segs[j][-1:].isspace():
                j += 1
            levels.append(".".join(segs[i:j + 1]) if j < len(segs) else ".".join(segs[i:j]))
            i = j + 1 if j < len(segs) else j
        else:
            levels.append(segs[i])
            i += 1
    return levels


def _parse_declared_range(data_type: str | None, width: int | None) -> tuple[int, int] | None:
    if data_type is None or width is None:
        return None
    m = _RANGE.search(data_type)
    if m is None:
        return None
    left, right = int(m.group(1)), int(m.group(2))
    return (left, right) if abs(left - right) + 1 == width else None


def _offsets_of(select: tuple[int, int], decl: tuple[int, int]) -> tuple[int, int]:
    left, right = decl
    low, high = min(left, right), max(left, right)
    if select[0] != select[1] and (select[0] > select[1]) != (left > right):
        raise ResolveError("BAD_SELECT",
                           f"select [{select[0]}:{select[1]}] runs opposite to declared range [{left}:{right}]")
    def to_off(i: int):
        if i < low or i > high:
            raise ResolveError("BAD_SELECT", f"bit {i} outside declared range [{left}:{right}]")
        return (i - right) if left >= right else (right - i)
    a, b = to_off(select[0]), to_off(select[1])
    return (min(a, b), max(a, b))


def _split_select(path: str) -> tuple[str, tuple[str, int, int] | None]:
    """Split a trailing bit-select off a path. Returns (base, select), where
    select is ('decl', a, b) for a declared index `sig[a:b]`, ('offset', a, b)
    for a raw flattened offset `sig@[a:b]`, or None."""
    m = _OFFSET_SELECT.match(path)
    if m is not None:
        base, a, b = m.group(1), int(m.group(2)), m.group(3)
        return base, ("offset", a, a if b is None else int(b))
    m = _BIT_SELECT.match(path)
    if m is not None:
        base, a, b = m.group(1), int(m.group(2)), m.group(3)
        return base, ("decl", a, a if b is None else int(b))
    return path, None


def _resolve_select(select, net) -> tuple[str | None, tuple[int, int] | None]:
    """Turn a parsed select into (display spell, flattened window). A declared
    index needs the net's single declared range; a raw @[..] offset does not."""
    if select is None:
        return None, None
    kind, a, b = select
    if kind == "offset":
        spell = f"@[{a}]" if a == b else f"@[{a}:{b}]"
        lo, hi = min(a, b), max(a, b)
        width = net["width"]
        if width is not None and (lo < 0 or hi >= width):
            raise ResolveError("BAD_SELECT",
                               f"offset @[{a}:{b}] outside width {width}")
        return spell, (lo, hi)
    decl = _parse_declared_range(net["data_type"], net["width"])
    if decl is None:
        raise ResolveError("BAD_SELECT",
                           f"{net['net_name']} has no single declared range; "
                           f"use @[lo:hi] with flattened bit offsets")
    window = _offsets_of((a, b), decl)   # also range-checks a and b
    spell = f"[{a}]" if a == b else f"[{a}:{b}]"
    return spell, window


def _candidates(cursor, node: int, inst: int | None) -> list[str]:
    kids = [r["node_name"] for r in cursor.execute(sql.load("children_of"), {"parent": node})]
    if inst is not None:
        kids += [r["net_name"] for r in cursor.execute(sql.load("nets_of"), {"inst_id": inst})]
    return sorted(set(kids))


def _child(cursor, node: int, name: str):
    return cursor.execute(sql.load("child_node"), {"parent": node, "name": name}).fetchone()


def _resolve_walk(cursor, root: int, levels: list[str], leaf: str) -> dict | None:
    """Walk the tree down `levels`, then find `leaf` as a net of the
    instance reached. Returns None when the path does not resolve."""
    root_node = cursor.execute(sql.load("node_by_id"), {"node_id": root}).fetchone()
    if root_node is None:
        return None
    node = root_node["node_id"]
    inst = root_node["inst_id"]
    below: list[str] = []
    folded: list[str] = []

    i = 0
    while i < len(levels):
        level = levels[i]
        child = _child(cursor, node, level)
        if child is None:
            # Not a tree level: a subroutine scope, an escaped net name, or
            # a generate net carried on the enclosing instance. Everything
            # from here on folds into the local net name.
            if folded:
                return None
            rest = levels[i:]
            break
        kind = child["node_kind"]
        if kind in ("instance", "root"):
            below.extend(folded)
            folded = []
            below.append(child["node_name"])
            node = child["node_id"]
            inst = child["inst_id"]
        elif kind == "generate":
            folded.append(child["node_name"])
            node = child["node_id"]
        else:
            return None  # primitive, unresolved — nothing below it
        i += 1
    else:
        rest = []

    local = ".".join(folded + rest + [leaf])
    row = cursor.execute(sql.load("net_by_name"), {"inst_id": inst, "name": local}).fetchone()
    if row is not None:
        return {"net": dict(row), "below": below, "local": local, "inst": inst}
    if local.startswith("\\"):
        bare = local[1:].rstrip()
        row = cursor.execute(sql.load("net_by_name"), {"inst_id": inst, "name": bare}).fetchone()
        if row is not None:
            return {"net": dict(row), "below": below, "local": bare, "inst": inst}
    return None


def _above_the_design(cursor, root: int, root_inst: int | None, root_name: str,
                      levels: list[str]) -> int | None:
    for i, level in enumerate(levels):
        if level == root_name:
            return i
        if _child(cursor, root, level) is not None:
            return i
        if i + 1 == len(levels) and root_inst is not None:
            net = cursor.execute(sql.load("net_exists"),
                                 {"inst_id": root_inst, "name": level}).fetchone()
            if net is not None:
                return i
    return None


def _diagnose(cursor, root: int, inst: int | None, levels: list[str]) -> dict:
    node = root
    valid = []
    for level in levels:
        child = _child(cursor, node, level)
        if child is not None and child["node_kind"] in ("instance", "root", "generate"):
            valid.append(level)
            node = child["node_id"]
            if child["node_kind"] in ("instance", "root"):
                inst = child["inst_id"]
        else:
            return {"valid_prefix": valid, "failing_segment": level,
                    "candidates": _candidates(cursor, node, inst)}
    return {"valid_prefix": valid, "failing_segment": "leaf",
            "candidates": _candidates(cursor, node, inst)}


def resolve(cursor, signal: str, top: str = "") -> ResolvedSignal:
    base_path, select = _split_select(signal)
    all_levels = _levels_of(base_path)
    if not all_levels:
        raise ResolveError("SIGNAL_NOT_FOUND", f"empty path '{signal}'")

    roots = cursor.execute(sql.load("tops")).fetchall()
    if not roots:
        raise ResolveError("NO_TOP", "this database elaborated no top")
    if top:
        root_row = next((r for r in roots if r["node_name"] == top), None)
        if root_row is None:
            names = [r["node_name"] for r in roots]
            raise ResolveError("NO_TOP", f"no top named '{top}'; elaborated tops: {names}")
    else:
        root_row = roots[0]
    root_id, root_name = root_row["node_id"], root_row["node_name"]
    root = cursor.execute(sql.load("node_by_id"), {"node_id": root_id}).fetchone()
    root_inst = root["inst_id"] if root else None

    above = _above_the_design(cursor, root_id, root_inst, root_name, all_levels)
    reached = above is not None
    rest = all_levels[above:] if above is not None else all_levels
    if rest and rest[0] == root_name:
        rest = rest[1:]

    if not rest:
        raise ResolveError("SIGNAL_NOT_FOUND",
                           f"'{signal}' names only the root; try "
                           f"{_candidates(cursor, root_id, root_inst)[:10]}")

    # Try every split of the remaining levels into (tree prefix, leaf name).
    # The leaf may itself contain dots (generate/subroutine segments, an
    # escaped identifier), so the split that resolves wins.
    for split in range(len(rest) - 1, -1, -1):
        result = _resolve_walk(cursor, root_id, rest[:split], ".".join(rest[split:]))
        if result is not None:
            net = result["net"]
            below = result["below"]
            local = result["local"]
            full_path = ".".join([root_name] + below + [local])
            spell, window = _resolve_select(select, net)
            return ResolvedSignal(
                net_id=net["net_id"],
                inst_id=net["inst_id"],
                net_name=net["net_name"],
                node_path=".".join([root_name] + below),
                full_path=full_path + (spell or ""),
                width=net["width"],
                spell=spell,
                window=window,
            )

    if not reached:
        raise ResolveError("SIGNAL_NOT_FOUND",
                           f"'{signal}' does not name a signal here; no level of the path matched this design")
    diag = _diagnose(cursor, root_id, root_inst, rest)
    raise ResolveError("SIGNAL_NOT_FOUND",
                       f"'{signal}' does not name a signal: "
                       f"'{diag['failing_segment']}' is not at "
                       f"{'.'.join([root_name] + diag['valid_prefix']) or root_name}. "
                       f"Try: {diag['candidates'][:10]}")

# --- cone ------------------------------------------------------
FOLLOW_ALL = -1


@dataclass
class Facts:
    clocked: set[int] = None
    latch: set[int] = None
    dead: set[int] = None            # stmt_ids under a statically-dead branch
    call_parent: dict = None
    body_local: set[int] = None


def load_facts(cursor) -> Facts:
    f = Facts()
    state_rows = cursor.execute(sql.load("state_elements")).fetchall()
    f.clocked = {r["net_id"] for r in state_rows if r["kind"] == "clocked"}
    f.latch = {r["net_id"] for r in state_rows if r["kind"] == "latch"}
    f.dead = {r["stmt_id"] for r in cursor.execute(sql.load("dead_stmts"))}
    f.call_parent = {r["call_site_id"]: r["parent_call_site_id"]
                     for r in cursor.execute(sql.load("call_parents"))}
    f.body_local = {r["net_id"] for r in cursor.execute(sql.load("body_local"))}
    return f


def _ctl_left(ctl_depth: int | None, follow_ctl: bool) -> int:
    """Normalize the CLI control options into one traversal budget:
    0 means stop at control edges, FOLLOW_ALL means follow them all."""
    if ctl_depth is not None:
        return ctl_depth
    return FOLLOW_ALL if follow_ctl else 0


def _stop_nets(facts: Facts, comb: bool, through_latch: bool) -> set[int]:
    """Nets a combinational walk must stop at, resolved once from the options."""
    if not comb:
        return set()
    stop = set(facts.clocked)
    if not through_latch:
        stop |= set(facts.latch)
    return stop


def _admissible(facts: Facts, row_site: int | None, ctx: int | None) -> bool:
    if row_site is None or ctx is None:
        return True
    return row_site == ctx or facts.call_parent.get(row_site) == ctx


def _next_ctx(facts: Facts, row: dict, ctx: int | None, far: int) -> int | None:
    site = row.get("call_site_id")
    if site is None:
        return ctx if far in facts.body_local else None
    if row.get("edge_kind") == "procedure":
        leaving = ctx == site
        outer = facts.call_parent.get(site)
        nxt = outer if leaving else site
        return nxt if far in facts.body_local else None
    return site if far in facts.body_local else None


def _arcs_batch(cursor, name: str, nets: list[int]) -> list[dict]:
    text, values = sql.fill(name, nets)
    return [dict(r) for r in cursor.execute(text, values)]


def _advance(facts: Facts, row: dict, ctx: int | None, ctl_left: int,
             window, stop_nets: set[int]):
    """Walk one edge row `near -> far`: returns (far_net, far_window,
    next_ctx, next_ctl, widened, unreachable) or None when the edge
    cannot be traversed."""
    if not _admissible(facts, row.get("call_site_id"), ctx):
        return None
    is_control = row.get("edge_kind") == "control"
    if is_control and ctl_left == 0:
        return None
    # A condition gates the whole statement; it is not bit-mappable.
    far_window = None
    if not is_control:
        far_window = propagate(window,
                               row["near_lo"], row["near_hi"],
                               row["far_lo"], row["far_hi"],
                               row["map_kind"])
        if far_window is SKIP:
            return None
    unreachable = row["stmt_id"] in facts.dead
    far_net = row["far_net_id"]
    ends_at_state = far_net in stop_nets
    if unreachable or ends_at_state:
        return (far_net, far_window, None, ctl_left,
                far_window is None and not is_control, unreachable)
    nctx = _next_ctx(facts, row, ctx, far_net)
    nctl = ctl_left - 1 if is_control and ctl_left >= 0 else ctl_left
    return (far_net, far_window, nctx, nctl,
            far_window is None and not is_control, unreachable)


def _cone_bfs(cursor, facts: Facts, name: str, start: int,
              ctl_left: int, stop_nets: set[int],
              depth: int, start_window) -> list[dict]:
    """BFS with call-site isolation, state-element and dead-code pruning.
    State is (net, ctx, ctl_left, window); coverage keeps each net's walked
    bits so the same bits are never re-walked."""
    covered: dict = {}
    uncovered(covered, (start, None, ctl_left), start_window)
    frontier = [(start, None, ctl_left, start_window)]
    edges = []
    d = 0
    while frontier and (depth == 0 or d < depth):  # depth 0 walks to closure
        d += 1
        nets = [net for net, _, _, _ in frontier]
        rows = _arcs_batch(cursor, name, nets)
        by_signal: dict[int, list[dict]] = {}
        for r in rows:
            by_signal.setdefault(r["near_net_id"], []).append(r)

        next_frontier = []
        for net, ctx, ctl_left, window in frontier:
            for r in by_signal.get(net, []):
                step = _advance(facts, r, ctx, ctl_left, window, stop_nets)
                if step is None:
                    continue
                far_net, far_window, nctx, nctl, widened, unreachable = step
                r["_depth"] = d
                r["_cur_window"] = window
                r["_far_window"] = far_window
                r["_widened"] = widened
                r["_unreachable"] = unreachable
                r["ends_at_state"] = far_net in stop_nets
                edges.append(r)
                if unreachable or r["ends_at_state"]:
                    continue
                for part in uncovered(covered, (far_net, nctx, nctl), far_window):
                    next_frontier.append((far_net, nctx, nctl, part))
        frontier = next_frontier
    return edges


def cone_walk(cursor, db: Db, signal: str, direction: str, depth: int,
              no_ctl: bool, comb: bool, through_latch: bool,
              follow_ctl: bool, ctl_depth: int | None, top: str) -> dict:
    sig = resolve(cursor, signal, top)
    facts = load_facts(cursor)
    bfs_name = "fanin_bfs" if direction == "driver" else "fanout_bfs"
    raw = _cone_bfs(cursor, facts, bfs_name, sig.net_id,
                    _ctl_left(ctl_depth, follow_ctl), _stop_nets(facts, comb, through_latch),
                    depth, sig.window)
    edges, nodes = _name_edges(cursor, raw, direction)
    data = {
        "start": sig.full_path,
        "direction": direction,
        "granularity": "bit" if sig.window else "net",
        "start_window": list(sig.window) if sig.window else None,
        "max_depth": None if depth == 0 else depth,
        "comb": comb,
        "through_latch": through_latch,
        "no_ctl": no_ctl,
        "follow_ctl": follow_ctl,
        "ctl_depth": ctl_depth,
        "nodes": nodes,
        "edges": edges,
    }
    summary = {
        "nodes": len(nodes),
        "edges": len(edges),
        "stopped_at_state": sum(1 for e in edges if e["ends_at_state"]),
        "max_depth_reached": max((e["depth"] for e in edges), default=0),
        "control_edges": sum(1 for e in edges if e["control"]),
    }
    return {"data": data, "summary": summary, "diagnostics": []}


def _name_edges(cursor, raw: list[dict], direction: str):
    net_ids = set()
    for r in raw:
        net_ids.add(r["src_net_id"])
        net_ids.add(r["dst_net_id"])
    names = net_names(cursor, net_ids)
    src_reader = Source(cursor)
    edges = []
    for r in raw:
        src, tgt = r["src_net_id"], r["dst_net_id"]
        kind = r.get("edge_kind")
        file_path, line = r.get("file_path"), r.get("src_line")
        statement = src_reader.line(file_path, line)[0] if file_path and line else None
        # The frontier net's window sits on the near end; the far net's on the
        # other side. For a fan-in the frontier is the target, for a fan-out the source.
        cur_win, far_win = r.get("_cur_window"), r.get("_far_window")
        target_win, source_win = (cur_win, far_win) if direction == "driver" else (far_win, cur_win)
        edges.append({
            "source": names.get(src, f"<net {src}>"),
            "target": names.get(tgt, f"<net {tgt}>"),
            "kind": kind,
            "edge_source": r.get("edge_source"),
            "depth": r["_depth"],
            "boundary": r.get("edge_source") == "conn_arc" or kind in ("connection", "connection_expression"),
            "control": kind == "control",
            "ends_at_state": r.get("ends_at_state", False),
            "unreachable": r.get("_unreachable", False),
            "source_window": list(source_win) if source_win else None,
            "target_window": list(target_win) if target_win else None,
            "widened": r.get("_widened", False),
            "file": file_path,
            "line": line,
            "statement": statement,
        })
    depth_map = {}
    for e in edges:
        if direction == "driver":
            depth_map.setdefault(e["source"], e["depth"])
            depth_map.setdefault(e["target"], e["depth"] - 1)
        else:
            depth_map.setdefault(e["source"], e["depth"] - 1)
            depth_map.setdefault(e["target"], e["depth"])
    nodes = [{"path": n, "depth": d}
             for n, d in sorted(depth_map.items(), key=lambda kv: (kv[1], kv[0]))]
    return edges, nodes


def _goal_matches(net_id: int, window: tuple[int, int] | None,
                  goal_id: int, goal_window: tuple[int, int] | None) -> bool:
    if net_id != goal_id:
        return False
    if goal_window is None:
        return True
    if window is None:
        return False
    return max(window[0], goal_window[0]) <= min(window[1], goal_window[1])


def _path_bfs(cursor, facts: Facts, start_id: int, goal_id: int,
              start_window, goal_window, direction: str,
              ctl_left: int, stop_nets: set[int], max_depth: int = 0):
    """Shortest path via BFS, same pruning as the cone walk. `direction` is
    "forward" (fanout from the start net) or "reverse" (fanin from the start
    net). Returns (trail, precision_lost) where trail is a list of
    (net_id, window, edge) from start to goal, or None."""
    if _goal_matches(start_id, start_window, goal_id, goal_window):
        return [(start_id, start_window, None)], False
    # Reverse search starts at the target.  If the target is a state element
    # and --comb is active, prune it now so the semantics match the forward
    # direction (which would never *enter* this state on the way to the goal).
    if direction == "reverse" and start_id in stop_nets:
        return None, False
    bfs_name = "fanout_bfs" if direction == "forward" else "fanin_bfs"
    start = (start_id, None, ctl_left, start_window)
    visited = {start}
    parents: dict = {}
    frontier = [start]
    precision_lost = False
    steps = 0
    while frontier and (max_depth == 0 or steps < max_depth):
        nets = [n for n, _, _, _ in frontier]
        rows = _arcs_batch(cursor, bfs_name, nets)
        by_signal: dict[int, list[dict]] = {}
        for r in rows:
            by_signal.setdefault(r["near_net_id"], []).append(r)
        next_frontier = []
        for net, ctx, ctl_left, window in frontier:
            for r in by_signal.get(net, []):
                step = _advance(facts, r, ctx, ctl_left, window, stop_nets)
                if step is None:
                    continue
                far_net, far_window, nctx, nctl, widened, unreachable = step
                if unreachable:
                    continue          # a path never routes through dead code
                key = (far_net, nctx, nctl, far_window)
                if key in visited:
                    continue
                visited.add(key)
                row_copy = dict(r)
                row_copy["_widened"] = widened
                parents[key] = ((net, ctx, ctl_left, window), row_copy)
                is_goal = far_net == goal_id
                # Forward cannot enter a state (including a state target).
                if direction == "forward" and far_net in stop_nets:
                    continue
                if _goal_matches(far_net, far_window, goal_id, goal_window):
                    trail = []
                    at = key
                    while at is not None:
                        entry = parents.get(at)
                        if entry is None:
                            trail.append((at[0], at[3], None))
                            break
                        parent_state, edge = entry
                        trail.append((at[0], at[3], edge))
                        at = parent_state
                    return trail[::-1], False
                if goal_window is not None and is_goal and far_window is None:
                    precision_lost = True
                    continue
                # Reverse: source reached without exact match, or a state
                # that is not the source goal, is the end of the walk.
                if direction == "reverse" and (is_goal or far_net in stop_nets):
                    continue
                next_frontier.append(key)
        frontier = next_frontier
        steps += 1
    return None, precision_lost


def cone_path(db: Db, from_sig: str, to_sig: str, max_depth: int = 0,
              no_ctl: bool = False, comb: bool = False, through_latch: bool = False,
         follow_ctl: bool = False, ctl_depth: int | None = None, top: str = "") -> dict:
    cur = db.conn.cursor()
    f = resolve(cur, from_sig, top)
    t = resolve(cur, to_sig, top)
    facts = load_facts(cur)
    ctl_left = _ctl_left(ctl_depth, follow_ctl)
    stop_nets = _stop_nets(facts, comb, through_latch)
    reverse = f.window is None and t.window is not None
    if reverse:
        trail, precision_lost = _path_bfs(
            cur, facts, t.net_id, f.net_id, t.window, f.window, "reverse",
            ctl_left, stop_nets, max_depth)
    else:
        trail, precision_lost = _path_bfs(
            cur, facts, f.net_id, t.net_id, f.window, t.window, "forward",
            ctl_left, stop_nets, max_depth)
    found = trail is not None
    if found and reverse:
        trail = trail[::-1]
        # Each state carried the edge from its search-order parent.  After
        # reversing to source -> target, move each edge onto the state that
        # owns its source side, so the downstream renderer stays direction-agnostic.
        for i in range(len(trail) - 1, 0, -1):
            net, win, _ = trail[i]
            trail[i] = (net, win, trail[i - 1][2])
        trail[0] = (trail[0][0], trail[0][1], None)
    edges = []
    nodes = []
    if found:
        net_seq = [n for n, _, _ in trail]
        names = net_names(cur, net_seq)
        nodes = [names.get(n, f"<net {n}>") for n in net_seq]
        src_reader = Source(cur)
        for (a, a_win, _), (b, b_win, edge) in zip(trail, trail[1:]):
            file_path = edge.get("file_path") if edge else None
            line = edge.get("src_line") if edge else None
            kind = edge.get("edge_kind") if edge else None
            edges.append({
                "source": names.get(edge["src_net_id"], f"<net {edge['src_net_id']}>") if edge else names.get(a, f"<net {a}>"),
                "target": names.get(edge["dst_net_id"], f"<net {edge['dst_net_id']}>") if edge else names.get(b, f"<net {b}>"),
                "source_window": list(a_win) if a_win else None,
                "target_window": list(b_win) if b_win else None,
                "widened": bool(edge.get("_widened")) if edge else False,
                "kind": kind,
                "file": file_path,
                "line": line,
                "statement": src_reader.line(file_path, line)[0] if file_path and line else None,
            })
    reason = "bit_precision_lost" if precision_lost and not found else None
    data = {
        "from": f.full_path,
        "to": t.full_path,
        "from_window": list(f.window) if f.window else None,
        "to_window": list(t.window) if t.window else None,
        "granularity": "bit" if (f.window is not None or t.window is not None) else "net",
        "found": found,
        "reason": reason,
        "length": len(trail) - 1 if found else 0,
        "nodes": nodes,
        "edges": edges,
    }
    summary = {"found": found, "length": len(trail) - 1 if found else 0}
    if reason:
        summary["reason"] = reason
    return {"data": data, "summary": summary, "diagnostics": []}

# --- commands --------------------------------------------------
def _plural(n: int, word: str) -> str:
    return f"{n} {word}" + ("" if n == 1 else "s")


def info(db: Db) -> dict:
    cur = db.conn.cursor()
    seal = cur.execute(sql.load("info")).fetchone()
    sources = cur.execute(sql.load("info_sources")).fetchall()
    unresolved = cur.execute(sql.load("info_unresolved")).fetchone()
    rows = []
    stale = missing = 0
    for s in sources:
        src, digest, state = source_state(cur, s["file_path"])
        rows.append({"path": s["src_path"], "state": state})
        stale += state == "stale"
        missing += state == "missing"
    data = {
        "path": db.path,
        "schema_version": seal["schema_version"],
        "producer": {
            "tool": seal["tool"],
            "tool_version": seal["tool_version"],
            "slang_version": seal["slang_version"],
            "revision": seal["producer_revision"],
            "config_digest": seal["config_digest"],
        },
        "top": seal["top"],
        "analysis": {
            "status": seal["analysis_status"],
            "error_count": seal["error_count"],
            "unresolved_count": seal["unresolved_count"],
            "empty_procedure_count": seal["empty_procedure_count"],
            "duplicate_path_count": seal["duplicate_path_count"],
            "recursion_count": seal["recursion_count"],
            "truncated_call_count": seal["truncated_call_count"],
            "checker_inst_count": seal["checker_inst_count"],
            "unanalysed_inst_count": seal["unanalysed_inst_count"],
            "unresolved_ref_reads": unresolved["unresolved_reads"],
            "unresolved_ref_writes": unresolved["unresolved_writes"],
        },
        "sources": rows,
    }
    summary = {
        "schema_version": seal["schema_version"],
        "analysis_status": seal["analysis_status"],
        "sources": len(rows),
        "sources_stale": stale,
        "sources_missing": missing,
    }
    return {"data": data, "summary": summary, "diagnostics": []}


def tree(db: Db, scope: str | None, depth: int = 3, limit: int = 0) -> dict:
    cur = db.conn.cursor()
    if scope is None:
        root = cur.execute(sql.load("tops")).fetchone()
        if root is None:
            raise ResolveError("NO_TOP", "this database elaborated no top")
        node_id, path = root["node_id"], root["node_name"]
    else:
        try:
            # A net names a scope: the instance that declares it.
            sig = resolve(cur, scope)
            node_id, path = sig.inst_id, sig.node_path
        except ResolveError:
            # Not a net: try the tree level itself.
            row = cur.execute(sql.load("node_by_path"), {"node_path": scope}).fetchone()
            if row is None:
                raise ResolveError("SCOPE_NOT_FOUND", f"'{scope}' does not name a scope")
            node_id, path = row["node_id"], row["node_path"]
    walk_depth = depth if depth > 0 else 1_000_000
    rows = cur.execute(sql.load("tree"), {"root_node_id": node_id, "max_depth": walk_depth}).fetchall()
    levels = []
    for r in rows:
        levels.append({
            "path": r["path"],
            "kind": r["node_kind"],
            "module": r["module_name"] or r["def_name"],
            "depth": r["depth"],
            "nets": r["nets"],
            "children": r["children"],
        })
    shown = levels if limit == 0 else levels[:limit]
    data = {"root": path, "max_depth": None if depth == 0 else depth, "levels": shown}
    summary = {
        "levels": len(levels),
        "shown": len(shown),
        "truncated": len(levels) > len(shown),
        "depth_truncated": depth > 0 and any(l["depth"] >= depth and l["children"] > 0 for l in levels),
        "limit": limit,
    }
    return {"data": data, "summary": summary, "diagnostics": []}


def find(db: Db, pattern: str, kind: str = "net", limit: int = 200) -> dict:
    cur = db.conn.cursor()
    root = cur.execute(sql.load("tops")).fetchone()
    root_path = root["node_name"] if root else ""
    # Fetch one past the limit to tell truncation from an exact fill; limit 0
    # means all, which SQLite's LIMIT reads as -1.
    probe = limit + 1 if limit > 0 else -1
    if kind == "net":
        rows = cur.execute(sql.load("find_net"),
                           {"pattern": pattern, "root_path": root_path, "limit": probe}).fetchall()
        hits = [{"path": r["full_path"], "what": "net",
                 "detail": f"{r['decl_kind']}, {_plural(r['width'], 'bit')}"
                           if r["width"] is not None else r["decl_kind"]}
                for r in rows]
    elif kind == "instance":
        rows = cur.execute(sql.load("find_instance"),
                           {"pattern": pattern, "root_path": root_path, "limit": probe}).fetchall()
        hits = [{"path": r["node_path"], "what": r["node_kind"], "detail": r["module_name"] or r["def_name"]}
                for r in rows]
    else:  # module
        rows = cur.execute(sql.load("find_module"), {"pattern": pattern, "limit": probe}).fetchall()
        hits = [{"path": r["name"], "what": r["def_kind"],
                 "detail": _plural(r["occurrences"], "instance")}
                for r in rows]
    truncated = limit > 0 and len(hits) > limit
    if truncated:
        hits = hits[:limit]
    data = {"pattern": pattern, "kind": kind, "hits": hits}
    summary = {"hits": len(hits), "shown": len(hits), "truncated": truncated, "limit": limit}
    return {"data": data, "summary": summary, "diagnostics": []}


def _provenance(row: dict, index: int, dep_kind: str | None) -> str:
    role = ":control" if dep_kind == "control" else ""
    if row.get("stmt_id") is not None:
        return f"s{row['stmt_id']}{role}"
    if row.get("conn_id") is not None:
        return f"c{row['conn_id']}"
    if row.get("prim_id") is not None:
        return f"p{row['prim_id']}"
    if row.get("term_id") is not None:
        return f"t{row['term_id']}"
    if row.get("proc_id") is not None:
        return f"proc{row['proc_id']}"
    return f"row{index}"


def _gates(cur, stmt_id: int | None, source: Source) -> tuple[list[dict], bool]:
    if stmt_id is None:
        return [], False
    rows = cur.execute(sql.load("trace_gates"), {"stmt_id": stmt_id}).fetchall()
    gates = []
    unreachable = False
    for r in rows:
        if r["static_taken"] == 0:
            unreachable = True
        iteration = None
        if r["iter_name"] and r["iter_first"] is not None and r["iter_step"] is not None and r["iter_count"] is not None:
            iteration = f"{r['iter_name']} = {r['iter_first']}, step {r['iter_step']}, {r['iter_count']} iteration(s)"
        elif r["iter_name"]:
            iteration = r["iter_name"]
        gates.append({
            "kind": r["branch_kind"],
            "sense": r["sense"],
            "case_kind": r["case_kind"],
            "check": r["check_kind"],
            "ordinal": r["ordinal"],
            "labels": r["labels"],
            "reads": r["reads"].split(",") if r["reads"] else [],
            "static_taken": r["static_taken"],
            "iteration": iteration,
            "line": r["src_line"],
        })
    return gates, unreachable


def _timing(cur, stmt_row) -> dict | None:
    if stmt_row is None or stmt_row["proc_id"] is None:
        return None
    proc_id = stmt_row["proc_id"]
    kind = cur.execute(sql.load("trace_prockind"), {"proc_id": proc_id}).fetchone()
    if kind is None:
        return None
    events = cur.execute(sql.load("trace_events"), {"proc_id": proc_id}).fetchall()
    return {
        "proc_kind": kind["proc_kind"],
        "events": [{"edge": e["edge_kind"], "signal": e["net_name"] or "<expression>"} for e in events],
    }


def _call_chain(cur, call_site_id: int | None) -> list[str]:
    if call_site_id is None:
        return []
    chain = []
    at = call_site_id
    while at is not None:
        row = cur.execute(sql.load("trace_calls"), {"call_site_id": at}).fetchone()
        if row is None:
            break
        chain.append(f"{row['subroutine_name']}()")
        at = row["parent_call_site_id"]
    chain.reverse()
    return chain


def _attach_far(hop: dict, far_net, far_ref, bit_mode: bool, far_widened: bool, far_window):
    """Record one arc's far end on its hop: the driven/read net (carrying its
    bit window, or marked widened, in bit mode), else an unresolved reference."""
    if far_net is not None:
        hop["signals"].add(far_net)
        if bit_mode:
            if far_widened:
                hop["_widened_far"].add(far_net)
            elif far_window is not None:
                hop["_far_windows"].setdefault(far_net, []).append(far_window)
    elif far_ref:
        hop["unresolved"].add(far_ref)


def trace(db: Db, signal: str, load: bool = False, ctl: bool = False, top: str = "") -> dict:
    cur = db.conn.cursor()
    sig = resolve(cur, signal, top)
    name = "trace_load" if load else "trace_driver"
    rows = cur.execute(sql.load(name), {"net_id": sig.net_id, "ctl": int(ctl)}).fetchall()
    source = Source(cur)
    hops = []
    procedures: list[dict] = []
    proc_index: dict[int, int] = {}
    far_ids = set()
    stmt_cache: dict[int, dict] = {}
    raw = [dict(r) for r in rows]

    # Serve every hop's scope from one whole-tree read (see node_paths.sql),
    # never a lookup per hop.
    node_paths: dict[int, str] = {}
    def scope_path(node_id: int) -> str | None:
        if not node_paths:
            node_paths.update((r["node_id"], r["node_path"])
                              for r in cur.execute(sql.load("node_paths")))
        return node_paths.get(node_id)

    # Bit mode: carry the requested window across each arc. SKIP rows feed
    # other bits (filtered out); None widens the far end to the whole net.
    # Control rows are gated the same way: they carry no bit correspondence.
    bit_mode = sig.window is not None
    arc_result: dict[int, object] = {}
    if bit_mode:
        for i, row in enumerate(raw):
            if row["dep_kind"] == "control":
                arc_result[i] = None
                continue
            arc_result[i] = propagate(sig.window,
                                      row["near_lo"], row["near_hi"],
                                      row["far_lo"], row["far_hi"],
                                      row["map_kind"])
    for index, row in enumerate(raw):
        # Bit mode: an arc that does not touch the requested window feeds
        # other bits and is filtered out of the answer entirely.
        if bit_mode and arc_result[index] is SKIP:
            continue
        kind = row["kind"]
        dk = row["dep_kind"]
        key = _provenance(row, index, dk)
        existing = next((h for h in hops if h["_key"] == key), None)
        far_net = row["far_net_id"]
        far_ref = row["far_ref"]
        if far_net is not None:
            far_ids.add(far_net)
        if bit_mode:
            res = arc_result[index]
            far_window = None if res is None else res     # None = widened whole
            # A condition gates the whole statement; it is not a value
            # mapping, so it is never "precision widened".
            far_widened = res is None and dk != "control"
        else:
            far_window, far_widened = None, False

        if existing is not None:
            _attach_far(existing, far_net, far_ref, bit_mode, far_widened, far_window)
            continue

        stmt_dict = None
        if row.get("stmt_id") is not None:
            if row["stmt_id"] not in stmt_cache:
                matches = cur.execute(sql.fill("trace_stmt", [row["stmt_id"]])[0],
                                      [row["stmt_id"]]).fetchall()
                stmt_cache.update({r["stmt_id"]: dict(r) for r in matches})
            stmt_dict = stmt_cache.get(row["stmt_id"])
        file_path = stmt_dict["file_path"] if stmt_dict and stmt_dict["file_path"] else row.get("file_path")
        line = stmt_dict["src_line"] if stmt_dict and stmt_dict["src_line"] else row.get("src_line")
        statement, source_state = source.line(file_path, line) if file_path else (None, "missing")
        scope = sig.full_path
        if stmt_dict:
            scope = scope_path(stmt_dict["scope_node_id"]) or sig.full_path
        gates, unreachable = _gates(cur, stmt_dict["stmt_id"] if stmt_dict else None, source)
        timing = _timing(cur, stmt_dict)
        call_chain = _call_chain(cur, stmt_dict["call_site_id"] if stmt_dict else None)
        raw_kind = (stmt_dict or {}).get("construct") or (stmt_dict or {}).get("stmt_kind") or kind
        procedure = None
        if stmt_dict and stmt_dict["proc_id"] is not None:
            pid = stmt_dict["proc_id"]
            if pid not in proc_index:
                writes = cur.execute(sql.load("trace_procwrites"),
                                     {"proc_id": pid, "net_id": sig.net_id}).fetchall()
                if len(writes) >= 2:
                    pk = cur.execute(sql.load("trace_prockind"), {"proc_id": pid}).fetchone()
                    proc_writes = []
                    for w in writes:
                        ws, ws_state = source.line(file_path, w["src_line"]) if file_path else (None, "missing")
                        proc_writes.append({
                            "sequence": w["sequence"],
                            "line": w["src_line"],
                            "statement": ws,
                            "bits": None,
                            "unconditional": w["branch_id"] is None,
                            "call_chain": _call_chain(cur, w["call_site_id"]),
                        })
                    proc_index[pid] = len(procedures)
                    procedures.append({"proc_kind": pk["proc_kind"] if pk else None, "writes": proc_writes})
                else:
                    proc_index[pid] = None
            procedure = proc_index.get(pid)
        hop = {
            "_key": key,
            "kind": kind,
            "raw_kind": raw_kind,
            "statement": statement,
            "source": source_state,
            "scope": scope,
            "file": file_path,
            "line": line,
            "boundary": kind in ("connection", "connection_expression") or far_ref is not None,
            "signals": set(),
            "unresolved": set(),
            "assign_kind": (stmt_dict or {}).get("assign_kind"),
            "sequence": (stmt_dict or {}).get("sequence"),
            "timing": timing,
            "gates": gates,
            "procedure": procedure,
            "unreachable": unreachable,
            "call_chain": call_chain,
            "_dep_kind": dk,
        }
        if bit_mode:
            hop["_far_windows"] = {}
            hop["_widened_far"] = set()
        _attach_far(hop, far_net, far_ref, bit_mode, far_widened, far_window)
        hops.append(hop)

    names = net_names(cur, far_ids)
    for h in hops:
        h["signals"] = sorted(names.get(n, f"<net {n}>") for n in h["signals"])
        h["unresolved"] = sorted(h["unresolved"])
        if bit_mode:
            h["far_windows"] = {}
            for n, w in h["_far_windows"].items():
                name = names.get(n, f"<net {n}>")
                h["far_windows"][name] = (
                    None if n in h["_widened_far"] else
                    [[lo, hi] for lo, hi in merge_intervals(w)])
            for n in h["_widened_far"]:
                h["far_windows"].setdefault(names.get(n, f"<net {n}>"), None)
            h["widened_far"] = sorted(
                names.get(n, f"<net {n}>") for n in h["_widened_far"])
            h.pop("_far_windows", None)
            h.pop("_widened_far", None)
        h.pop("_key", None)
        h["dep_kind"] = h.pop("_dep_kind", None)

    structural = [h for h in hops if h["kind"] not in ("alias", "control")]
    if not structural:
        status = "no_load_found" if load else "no_driver_found"
    elif all(h["kind"] in ("connection", "terminal") for h in structural):
        status = "boundary_only"
    else:
        status = "resolved"
    data = {
        "signal": sig.full_path,
        "direction": "load" if load else "driver",
        "granularity": "bit" if sig.window else "net",
        "start_window": list(sig.window) if sig.window else None,
        "bits": sig.spell,
        "width": sig.width,
        "status": status,
        "hops": hops,
        "procedures": procedures,
    }
    summary = {"status": status, "hops": len(hops), "structural_hops": len(structural)}
    return {"data": data, "summary": summary, "diagnostics": []}

# --- cli -------------------------------------------------------
TOOL = "rtltracer"

_HELP = """\
commands (each takes DB, the design database):
  info    DB              seal, sources, analysis status
  tree    DB [SCOPE]      hierarchy levels
  find    DB PATTERN      match nets by name glob
  trace   DB SIGNAL       one hop: who drives it
  fanin   DB SIGNAL       everything driving it, transitively
  fanout  DB SIGNAL       everything it drives, transitively
  path    DB FROM TO      shortest driver route between two signals

options by command:
  --json                        JSON instead of human text (any command)
  tree    --depth N (0=all)     --limit N (0=all)
  find    --instances|--modules match instances or modules instead of nets
          --limit N (0=all)
  trace   --load                readers instead of drivers
          --ctl                 include control (gating) arcs
  fanin / fanout / path:
          --depth N             max hops, 0 = unbounded
          --comb                stop at flops and latches
          --through-latch       with --comb, cross latches
          --no-ctl              drop control arcs
          --follow-ctl          follow control arcs transitively
          --ctl-depth N         follow control arcs, at most N levels
  --top NAME                    choose the top if several elaborated (trace + cones)

SIGNAL, FROM and TO are hierarchical paths (top.u_core.q); a leading testbench
scope is dropped. A trailing bit-select narrows fanin/fanout/path to those bits
-- q[17] or q[7:4] by declared index, q@[17] by flattened LSB offset. Add --json
to any command for the machine-readable envelope."""


class _Ink:
    """ANSI styling, but only for an interactive terminal (honours NO_COLOR).
    Piped or redirected output stays plain, so JSON and greps are untouched."""

    def __init__(self, stream):
        self.on = stream.isatty() and os.environ.get("NO_COLOR") is None

    def _p(self, code: str, s: str) -> str:
        return f"\033[{code}m{s}\033[0m" if self.on else s

    def bold(self, s): return self._p("1", s)
    def dim(self, s): return self._p("2", s)
    def red(self, s): return self._p("31", s)
    def green(self, s): return self._p("32", s)
    def yellow(self, s): return self._p("33", s)
    def cyan(self, s): return self._p("36", s)

    def state(self, s: str) -> str:
        good = {"resolved", "complete", "ok", "current"}
        warn = {"boundary_only", "partial", "hierarchy_only", "stale",
                "no_driver_found", "no_load_found"}
        return self.green(s) if s in good else self.yellow(s) if s in warn else self.red(s)


def _envelope(command: str, args: dict, status: str, data: dict, summary: dict,
              diagnostics: list, errors: list) -> str:
    body = {
        "tool": TOOL,
        "version": __version__,
        "status": status,
        "command": {"name": command, "args": args},
        "data": data,
        "diagnostics": diagnostics,
        "errors": errors,
        "summary": summary,
    }
    return json.dumps(body, ensure_ascii=False, indent=2) + "\n"


def _result(name: str, args: dict, outcome, json_mode: bool):
    if isinstance(outcome, Exception):
        if json_mode:
            out = _envelope(name, args, "error", None, None, [],
                            [{"code": outcome.code, "message": str(outcome)}])
            sys.stdout.write(out)
        else:
            _emit_error(str(outcome))
        return 1
    data, summary, diagnostics = outcome["data"], outcome["summary"], outcome["diagnostics"]
    if json_mode:
        out = _envelope(name, args, "ok", data, summary, diagnostics, [])
        sys.stdout.write(out)
        return 0
    # Human text
    sys.stdout.write(_human(name, data, summary))
    e = _Ink(sys.stderr)
    for d in diagnostics:
        if d.get("severity") == "warning":
            print(f"{e.yellow('warning:')} {d['message']}", file=sys.stderr)
    return 0


def _emit_error(msg: str):
    e = _Ink(sys.stderr)
    print(f"{e.red('error:')} {msg}", file=sys.stderr)


def _human(name: str, data: dict, summary: dict) -> str:
    c = _Ink(sys.stdout)
    lines = []

    def loc(e):
        s = f"{e['file']}:{e['line']}" if e.get("file") and e.get("line") else ""
        return c.dim(s)

    def plur(n, word):
        return f"{n} {word}" + ("" if n == 1 else "s")

    def field(k, v, hot=False):
        lab = (c.yellow if hot else c.dim)(f"{k:<12}")
        return f"      {lab}  {v}"

    def winbits(w):   # a bit window [lo] / [lo:hi] as LSB offsets, "" for whole
        if not w:
            return ""
        if isinstance(w[0], list):   # interval list: [[lo, hi], ...]
            parts = []
            for lo, hi in w:
                parts.append(f"{lo}:{hi}" if lo != hi else f"{lo}")
            return "@{" + ",".join(parts) + "}"
        # Internal windows are LSB-relative flattened offsets, so render them
        # with the @[..] spelling rather than a declared-index [..] select.
        return f"@[{w[0]}]" if w[0] == w[1] else f"@[{w[0]}:{w[1]}]"

    if name == "info":
        a = data["analysis"]
        prod = f"{data['producer']['tool']} {data['producer']['tool_version']}"
        lines.append(f"{c.bold('Database:')} {data['path']}")
        lines.append(f"{c.bold('Schema:  ')} v{data['schema_version']}  {c.dim('(' + prod + ')')}")
        lines.append(f"{c.bold('Top:     ')} {c.cyan(data['top'] or '(none)')}")
        lines.append(f"{c.bold('Analysis:')} {c.state(a['status'])}")
        for k in ("error_count", "empty_procedure_count", "duplicate_path_count", "truncated_call_count", "unanalysed_inst_count"):
            if a[k] > 0:
                lines.append(c.yellow(f"  short: {a[k]} {k.replace('_', ' ')}"))
        for k in ("unresolved_count", "checker_inst_count"):
            if a[k] > 0:
                lines.append(c.dim(f"  declined: {a[k]} {k.replace('_', ' ')}"))
        if a["recursion_count"] > 0:
            lines.append(c.yellow(f"  truncated: {plur(a['recursion_count'], 'recursive instance')}"))
        stale, missing = summary["sources_stale"], summary["sources_missing"]
        tail = c.yellow(f", {stale} stale, {missing} missing") if stale + missing > 0 else ""
        lines.append(f"{c.bold('Sources: ')} {plur(summary['sources'], 'file')}{tail}")
        for s in data["sources"]:
            if s["state"] in ("stale", "missing"):
                lines.append(f"  {c.state(s['state'])}: {s['path']}")
        lines.append("")
    elif name == "tree":
        levels = data["levels"]
        # A node is its parent's last child when the next line at its own depth
        # never comes before the walk pops to a shallower one.
        last = [True] * len(levels)
        for i, lv in enumerate(levels):
            d = lv["depth"]
            for j in range(i + 1, len(levels)):
                nd = levels[j]["depth"]
                if nd < d:
                    break
                if nd == d:
                    last[i] = False
                    break
        last_at = {}
        for i, lv in enumerate(levels):
            d = lv["depth"]
            last_at[d] = last[i]
            if d == 0:
                stem = ""
            else:
                rail = "".join("    " if last_at.get(k, True) else "│   " for k in range(1, d))
                stem = c.dim(rail + ("└── " if last[i] else "├── "))
            what = c.dim(lv["module"] or lv["kind"])
            nets = c.dim("  " + plur(lv["nets"], "net")) if lv["nets"] else ""
            lines.append(f"{stem}{c.cyan(lv['path'].split('.')[-1])}  {what}{nets}")
        if summary["truncated"]:
            lines.append(c.dim(f"\ntruncated: {summary['shown']}/{summary['levels']} levels"))
        if summary["depth_truncated"]:
            lines.append(c.dim(f"\nstopped at depth {data['max_depth']}"))
        lines.append("")
    elif name == "find":
        if not data["hits"]:
            lines.append(c.dim(f"no {data['kind']} matches '{data['pattern']}'"))
        for h in data["hits"]:
            detail = h.get("detail")
            lines.append(f"  {c.cyan(h['path'])}{'  ' + c.dim(detail) if detail else ''}")
        if summary["truncated"]:
            lines.append(c.dim(f"\ntruncated: first {summary['shown']}; raise --limit for more"))
        lines.append("")
    elif name == "trace":
        noun = "driver" if data["direction"] == "driver" else "reader"
        n = len(data["hops"])
        bits = f"{data['bits']} " if data.get("bits") else ""
        lines.append(f"{c.bold('signal')} {c.cyan(data['signal'])}  {bits}{c.dim('[' + str(data['width']) + ' bits]')}")
        count = c.bold(f"{n} {noun}" + ("" if n == 1 else "s"))
        st = data["status"]
        if st == "boundary_only":
            lines.append(f"{count}{c.yellow(', only at the module boundary')}")
        elif st in ("no_driver_found", "no_load_found"):
            lines.append(c.yellow(f"no {noun} found"))
        else:
            lines.append(count)
        lines.append("")
        for i, h in enumerate(data["hops"], 1):
            if i > 1:
                lines.append("")
            text = h["statement"] or c.dim(f"<{h['raw_kind']}>")
            lines.append(f"  {c.bold(f'[{i}]')} {text}")
            lines.append(field("kind", h["kind"]))
            if h.get("file") and h.get("line"):
                lines.append(field("location", c.dim(f"{h['file']}:{h['line']}")))
            if h["source"] not in ("current", "read"):
                lines.append(field("source", c.yellow(h["source"])))
            if h.get("timing"):
                ev = ", ".join(f"{e['edge']} {e['signal']}" for e in h["timing"]["events"])
                body = f"{h['timing']['proc_kind']} @({ev})" if ev else h["timing"]["proc_kind"]
                lines.append(field("timing block", body))
            for g in h.get("gates", []):
                cond = g["kind"]
                if g.get("sense"):
                    cond += f" ({g['sense']})"
                if g.get("labels"):
                    cond += f" = {g['labels']}"
                if g.get("reads"):
                    cond += f" [{', '.join(g['reads'])}]"
                if g.get("iteration"):
                    cond += f" iter {g['iteration']}"
                lines.append(field("condition", cond, hot=True))
            if h.get("unreachable"):
                lines.append(field("unreachable", c.red("constant condition rules this out"), hot=True))
            if h.get("call_chain"):
                lines.append(field("via", c.dim(" → ".join(h["call_chain"]))))
            arrow = "from" if data["direction"] == "driver" else "to"
            for s in h.get("signals", []):
                if data.get("granularity") == "bit":
                    if s in h.get("widened_far", []):
                        lines.append(field(arrow, c.cyan(s) + c.dim("[*]") + "  " + c.yellow("precision widened"), hot=True))
                    else:
                        w = h.get("far_windows", {}).get(s)
                        lines.append(field(arrow, c.cyan(s + (winbits(w) if w else ""))))
                else:
                    lines.append(field(arrow, c.cyan(s)))
            for s in h.get("unresolved", []):
                lines.append(field("unresolved", c.cyan(s), hot=True))
        for i, p in enumerate(data.get("procedures", [])):
            lines.append(c.dim(f"\n  procedure #{i + 1} ({p['proc_kind']}) writes {len(p['writes'])} times:"))
            for w in p["writes"]:
                bits = f"   bits {w.get('bits')}" if w.get("bits") else ""
                uncond = c.dim("   [ungated]") if w.get("unconditional") else ""
                chain = c.dim(f"   via {' → '.join(w.get('call_chain', []))}") if w.get("call_chain") else ""
                ln = f"{w.get('line') or '':>5}"
                lines.append(f"    {c.dim(ln)}  {w.get('statement') or '<assignment>'}{bits}{uncond}{chain}")
        lines.append("")
    elif name in ("fanin", "fanout"):
        lines.append(f"{c.bold(name)} of {c.cyan(data['start'])}")
        parts = [plur(summary["nodes"], "node"), plur(summary["edges"], "edge")]
        if data.get("comb"):
            parts.append("combinational")
        if summary.get("control_edges"):
            parts.append(plur(summary["control_edges"], "condition"))
        lines.append(c.dim(", ".join(parts)))
        for i, e in enumerate(data.get("edges", []), 1):
            lines.append("")
            src = e["source"] + winbits(e.get("source_window"))
            tgt = e["target"] + winbits(e.get("target_window"))
            arrow = f"{c.cyan(src)} {c.dim('→')} {c.cyan(tgt)}"
            lines.append(f"  {c.bold(f'[{i}]')} {arrow}")
            lines.append(field("depth", e["depth"]))
            lines.append(field("via", e["kind"], hot=e.get("control")))
            if e.get("widened"):
                lines.append(field("note", "precision widened: bit correspondence unavailable", hot=True))
            if e.get("ends_at_state"):
                lines.append(field("note", "stops at a state element", hot=True))
            if e.get("file") and e.get("line"):
                lines.append(field("location", loc(e)))
            if e.get("statement"):
                lines.append(field("code", e["statement"]))
        lines.append("")
    elif name == "path":
        lines.append(f"{c.bold('path')} {c.cyan(data['from'])} {c.dim('→')} {c.cyan(data['to'])}")
        if data["found"]:
            lines.append(c.green(f"found, {plur(data['length'], 'hop')}"))
            lines.append("")
            start_label = data['from']
            if data.get("granularity") == "bit" and data.get("edges"):
                w = data["edges"][0].get("source_window")
                if w:
                    start_label = data["edges"][0]["source"] + winbits(w)
            lines.append(f"  {c.cyan(start_label)}")
            for e in data.get("edges", []):
                lines.append(f"    {c.dim('│ via ' + (e['kind'] or '?'))}  {loc(e)}")
                if e.get("statement"):
                    lines.append(f"    {c.dim('│ ' + e['statement'])}")
                if e.get("widened"):
                    lines.append(f"    {c.dim('│')} {c.yellow('precision widened')}")
                lines.append(f"  {c.cyan(e['target'] + winbits(e.get('target_window')))}")
        else:
            if data.get("reason") == "bit_precision_lost":
                lines.append(c.yellow("No exact bit path found."))
                lines.append(c.dim("Source net was reached, but bit correspondence was lost along the path."))
            else:
                lines.append(c.yellow("no path found"))
        lines.append("")
    lines.append(c.dim(f"  [{summary.get('_ms', 0)} ms]"))
    return "\n".join(lines) + "\n"


def _resolve_opt(v: str | None, default=""):
    return v if v is not None else default


def main():
    p = argparse.ArgumentParser(
        prog=TOOL, formatter_class=argparse.RawDescriptionHelpFormatter,
        usage="%(prog)s [-h] [-V] COMMAND [ARGS]",
        description="Signal trace, driver and load analysis over an rtl-designdb "
                    "design database (schema v22).",
        epilog=_HELP)
    p.add_argument("-V", "--version", action="version", version=f"{TOOL} {__version__}")

    # -h anywhere, including after a subcommand, shows this one help.
    class _Help(argparse.Action):
        def __init__(self, option_strings, dest, **kw):
            super().__init__(option_strings, dest, nargs=0, default=argparse.SUPPRESS, **kw)

        def __call__(self, *_a, **_k):
            p.print_help()
            p.exit()

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("-h", "--help", action=_Help, help=argparse.SUPPRESS)
    common.add_argument("--json", action="store_true")

    walk_opts = argparse.ArgumentParser(add_help=False)  # fanin / fanout / path
    walk_opts.add_argument("--comb", action="store_true")
    walk_opts.add_argument("--through-latch", action="store_true")
    walk_opts.add_argument("--no-ctl", action="store_true")
    walk_opts.add_argument("--follow-ctl", action="store_true")
    walk_opts.add_argument("--ctl-depth", type=int, default=None, metavar="N")
    walk_opts.add_argument("--top", default="", metavar="NAME")

    # The one help text lives in _HELP; the auto per-command listing is hidden.
    sub = p.add_subparsers(dest="command", metavar="COMMAND", required=True,
                           help=argparse.SUPPRESS)

    def cmd(name, *parents):
        return sub.add_parser(name, parents=[common, *parents], add_help=False)

    pi = cmd("info")
    pi.add_argument("db", metavar="DB", type=Path)

    pt = cmd("tree")
    pt.add_argument("db", metavar="DB", type=Path)
    pt.add_argument("scope", nargs="?", default=None, metavar="SCOPE")
    pt.add_argument("--depth", type=int, default=3, metavar="N")
    pt.add_argument("--limit", type=int, default=0, metavar="N")

    pf = cmd("find")
    pf.add_argument("db", metavar="DB", type=Path)
    pf.add_argument("pattern", metavar="PATTERN")
    what = pf.add_mutually_exclusive_group()
    what.add_argument("--instances", action="store_true")
    what.add_argument("--modules", action="store_true")
    pf.add_argument("--limit", type=int, default=200, metavar="N")

    ptr = cmd("trace")
    ptr.add_argument("db", metavar="DB", type=Path)
    ptr.add_argument("signal", metavar="SIGNAL")
    ptr.add_argument("--load", action="store_true")
    ptr.add_argument("--ctl", action="store_true")
    ptr.add_argument("--top", default="", metavar="NAME")

    pfi = cmd("fanin", walk_opts)
    pfi.add_argument("db", metavar="DB", type=Path)
    pfi.add_argument("signal", metavar="SIGNAL")
    pfi.add_argument("--depth", type=int, default=4, metavar="N")

    pfo = cmd("fanout", walk_opts)
    pfo.add_argument("db", metavar="DB", type=Path)
    pfo.add_argument("signal", metavar="SIGNAL")
    pfo.add_argument("--depth", type=int, default=4, metavar="N")

    pp = cmd("path", walk_opts)
    pp.add_argument("db", metavar="DB", type=Path)
    pp.add_argument("from_signal", metavar="FROM")
    pp.add_argument("to_signal", metavar="TO")
    pp.add_argument("--depth", type=int, default=0, metavar="N")

    args = p.parse_args()
    try:
        db = open_db(str(args.db))
    except DbError as e:
        if args.json:
            sys.stdout.write(_envelope(args.command, {k: (str(v) if isinstance(v, Path) else v) for k, v in vars(args).items()}, "error", None, None, [],
                                       [{"code": e.code, "message": e.message}]))
        else:
            _emit_error(e.message)
        return 1

    cmd = args.command
    top = _resolve_opt(getattr(args, "top", None))
    json_mode = args.json

    try:
        _t0 = time.perf_counter()
        if cmd == "info":
            outcome = info(db)
        elif cmd == "tree":
            outcome = tree(db, args.scope, args.depth, args.limit)
        elif cmd == "find":
            kind = "module" if args.modules else ("instance" if args.instances else "net")
            outcome = find(db, args.pattern, kind, args.limit)
        elif cmd == "trace":
            outcome = trace(db, args.signal, args.load, args.ctl, top)
        elif cmd == "fanin":
            outcome = cone_walk(db.conn.cursor(), db, args.signal, "driver",
                                args.depth, args.no_ctl, args.comb, args.through_latch,
                                args.follow_ctl, args.ctl_depth, top)
        elif cmd == "fanout":
            outcome = cone_walk(db.conn.cursor(), db, args.signal, "load",
                                args.depth, args.no_ctl, args.comb, args.through_latch,
                                args.follow_ctl, args.ctl_depth, top)
        elif cmd == "path":
            outcome = cone_path(db, args.from_signal, args.to_signal,
                                args.depth, args.no_ctl, args.comb, args.through_latch,
                                args.follow_ctl, args.ctl_depth, top)
        else:
            raise DbError("BAD_COMMAND", f"unknown command: {cmd}")
        outcome["summary"]["_ms"] = int((time.perf_counter() - _t0) * 1000)
        rc = _result(cmd, {k: (str(v) if isinstance(v, Path) else v) for k, v in vars(args).items()}, outcome, json_mode)
    except (ResolveError, DbError) as e:
        # Convert to error envelope
        if hasattr(e, "code"):
            code = e.code
        else:
            code = "ERROR"
        if json_mode:
            sys.stdout.write(_envelope(cmd, {k: (str(v) if isinstance(v, Path) else v) for k, v in vars(args).items()}, "error", None, None, [],
                                       [{"code": code, "message": str(e)}]))
        else:
            _emit_error(str(e))
        rc = 1

    return rc


if __name__ == "__main__":
    sys.exit(main())
