#!/usr/bin/env python3
"""Bundle the rtltracer package into a single self-contained rtltracer.py.

Two jobs only: embed each sql/*.sql text (so the one file carries no sql/
directory), and concatenate the modules with their intra-package imports
stripped. It relies on the source keeping every top-level def/class name
unique across modules and using no module-qualified cross-module calls, and
refuses to emit if a name collides."""
from __future__ import annotations

import ast
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PKG = ROOT / "rtltracer"
OUT = ROOT / "dist" / "rtltracer.py"

# Concatenation order = dependency order (each module uses only earlier ones).
ORDER = ["__init__", "sql", "bits", "db", "source", "resolve", "cone", "commands", "cli"]


def _split(src: str):
    """(future_imports, stdlib_imports, body) for one module, dropping the
    module docstring and every `from rtltracer...` / `import rtltracer` line."""
    tree = ast.parse(src)
    lines = src.splitlines()
    drop: set[int] = set()
    futures: list[str] = []
    stdlib: list[str] = []
    if (tree.body and isinstance(tree.body[0], ast.Expr)
            and isinstance(getattr(tree.body[0], "value", None), ast.Constant)
            and isinstance(tree.body[0].value.value, str)):
        drop.update(range(tree.body[0].lineno, tree.body[0].end_lineno + 1))
    for node in tree.body:
        if isinstance(node, (ast.Import, ast.ImportFrom)):
            span = range(node.lineno, node.end_lineno + 1)
            text = "\n".join(lines[node.lineno - 1:node.end_lineno])
            if isinstance(node, ast.ImportFrom) and node.module == "__future__":
                futures.append(text)
            elif isinstance(node, ast.ImportFrom):
                if not (node.module and node.module.split(".")[0] == "rtltracer"):
                    stdlib.append(text)
            else:  # import X
                if not any(a.name.split(".")[0] == "rtltracer" for a in node.names):
                    stdlib.append(text)
            drop.update(span)
    body = "\n".join(ln for i, ln in enumerate(lines, 1) if i not in drop)
    return futures, stdlib, body.strip("\n")


def _defs(src: str) -> list[str]:
    return [n.name for n in ast.parse(src).body
            if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))]


def main() -> None:
    futures: list[str] = []
    stdlib: list[str] = []
    bodies: list[tuple[str, str]] = []
    seen_defs: dict[str, list[str]] = {}
    for mod in ORDER:
        src = (PKG / f"{mod}.py").read_text(encoding="utf-8")
        f, s, body = _split(src)
        futures += f
        stdlib += s
        bodies.append((mod, body))
        for name in _defs(src):
            seen_defs.setdefault(name, []).append(mod)

    dups = {n: m for n, m in seen_defs.items() if len(m) > 1}
    if dups:
        sys.exit(f"bundle refused: duplicate top-level names across modules: {dups}")

    imports: list[str] = []
    for line in stdlib:
        if line not in imports:
            imports.append(line)

    embed = {p.stem: p.read_text(encoding="utf-8")
             for p in sorted((PKG / "sql").glob("*.sql"))}

    parts = [
        "#!/usr/bin/env python3",
        '"""RTLTracer single-file bundle. Generated by scripts/bundle.py — '
        'edit the package, not this file."""',
    ]
    if any("annotations" in x for x in futures):
        parts.append("from __future__ import annotations")
    parts.append("\n".join(sorted(imports)))
    for mod, body in bodies:
        parts.append(f"\n# --- {mod} " + "-" * (58 - len(mod)))
        parts.append(body)
        if mod == "sql":
            parts.append("\n# --- embedded SQL (replaces the disk-backed loader) ---")
            parts.append("sql = _Sql({")
            for name, text in embed.items():
                parts.append(f"    {name!r}: {text!r},")
            parts.append("})")
    # cli's own `if __name__ == "__main__": sys.exit(main())` runs the tool.

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes, "
          f"{len(embed)} queries embedded)")


if __name__ == "__main__":
    main()
